import{state,update}from'./state.js';import{printers}from'./data/printers.js';import{materials}from'./data/materials.js';import{loadModel,dimensions}from'./model/load-model.js';import{dimensionsText}from'./model/units.js';import{applyTransform,rotate90,resetOrientation,placeNormal}from'./model/orientation.js';import{createViewer,modelThumbnail}from'./viewer/scene.js';import{printerFit}from'./analysis/fit.js';import{validateInWorker}from'./analysis/mesh-validation.js';import{addOverhangAttribute}from'./analysis/overhang.js';import{heatmapMaterial}from'./shaders/heatmap.js';import{saveModel,recentModels,removeModel,setting,setSetting}from'./storage/db.js';import{startAR}from'./ar/ar.js';
const $=s=>document.querySelector(s),viewer=createViewer($('#canvas'));let installPrompt,placeMode=false,isOpening=false;const alert=m=>{$('#notice-message').textContent=m;$('#notice').hidden=false};
const setLoading=(active,message='Načítám model…')=>{const loading=$('#loading');$('#loading-message').textContent=message;loading.hidden=!active;document.body.setAttribute('aria-busy',String(active))};
const waitForPaint=()=>new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve)));
async function displayVersion(){try{const response=await fetch('./version.json',{cache:'no-store'});if(!response.ok)throw Error();const {version}=await response.json();if(version)$('#app-version').textContent=`v${version}`}catch{/* The version bundled in the HTML remains visible offline. */}}
async function registerServiceWorker(){if(!('serviceWorker'in navigator))return;let hadController=Boolean(navigator.serviceWorker.controller);navigator.serviceWorker.addEventListener('controllerchange',()=>{if(!hadController){hadController=true;return}if(!$('#viewer').hidden&&state.currentModel)$('#update-banner').hidden=false;else location.reload()});try{const registration=await navigator.serviceWorker.register('./sw.js',{updateViaCache:'none'});await registration.update()}catch{alert('Offline režim se nepodařilo aktivovat.')}}
async function boot(){displayVersion();registerServiceWorker();const printerId=await setting('printer','mk4s'),materialId=await setting('material','pla');state.printer=printers.find(p=>p.id===printerId)||printers[1];state.material=materials.find(m=>m.id===materialId)||materials[0];for(const p of printers)$('#printer').add(new Option(p.name,p.id));for(const m of materials)$('#material').add(new Option(m.name,m.id));$('#printer').value=state.printer.id;$('#material').value=state.material.id;viewer.setBed(state.printer);renderRecents()}
async function open(blob,name,unit='mm',record){if(isOpening)return;isOpening=true;setLoading(true);try{await waitForPaint();const loaded=await loadModel(blob,name,unit);loaded.blob=blob;loaded.name=name;loaded.id=record?.id||crypto.randomUUID();update({currentModel:loaded,transform:{quaternion:record?.orientation||[0,0,0,1],position:[0,0,0]}});applyTransform(loaded.root);loaded.thumbnail=record?.thumbnail||modelThumbnail(loaded.root);viewer.setModel(loaded.root);const dims=dimensions(loaded.root);setLoading(true,'Analyzuji geometrii…');const summary=await validateInWorker(loaded.root);loaded.dimensions=dims;loaded.summary=summary;$('#home').hidden=true;$('#viewer').hidden=false;$('#title').textContent=name;$('#dimensions').textContent=dimensionsText(dims);await persist();refresh();}catch(e){alert(e.message)}finally{isOpening=false;setLoading(false)}}
async function persist(){const m=state.currentModel;if(!m)return;await saveModel({id:m.id,blob:m.blob,name:m.name,format:m.format,unit:m.unit,dimensions:m.dimensions,orientation:state.transform.quaternion,lastOpened:Date.now(),meshSummary:m.summary,thumbnail:m.thumbnail});renderRecents()}
function refresh(){const f=printerFit(state.currentModel.root,state.printer);$('#fit').textContent=f.fits?'Vejde se na tiskárnu':`Na tiskárnu se nevejde — ${f.issues.join(', ')}`;$('#mesh').textContent=`Síť: ${state.currentModel.summary.status} · hraniční hrany ${state.currentModel.summary.boundaryEdges} · nespojité hrany ${state.currentModel.summary.nonManifoldEdges} · degenerované trojúhelníky ${state.currentModel.summary.degenerateTriangles}`}
async function renderRecents(){const list=$('#recents');list.replaceChildren();try{for(const m of await recentModels()){const li=document.createElement('li');li.innerHTML=`<button class="recent"><img class="recent-preview" alt=""><span class="recent-copy"><b></b><small></small></span></button><button class="delete" aria-label="Odstranit">×</button>`;const image=li.querySelector('img');image.alt=`Náhled modelu ${m.name}`;li.querySelector('b').textContent=m.name;li.querySelector('small').textContent=`${m.format.toUpperCase()} · ${dimensionsText(m.dimensions)} · ${new Date(m.lastOpened).toLocaleDateString()} · ${m.meshSummary?.status||''}`;li.querySelector('.recent').onclick=()=>open(m.blob,m.name,m.unit,m);li.querySelector('.delete').onclick=async()=>{await removeModel(m.id);renderRecents()};list.append(li);if(m.thumbnail)image.src=m.thumbnail;else createMissingThumbnail(m,image)}}catch{alert('IndexedDB není dostupná; poslední modely nelze načíst.')}}
async function createMissingThumbnail(model,image){try{const loaded=await loadModel(model.blob,model.name,model.unit);applyTransform(loaded.root,model.orientation);model.thumbnail=modelThumbnail(loaded.root);image.src=model.thumbnail;await saveModel(model)}catch{image.alt=`Náhled modelu ${model.name} se nepodařilo vytvořit`}}
$('#file').onchange=e=>{const f=e.target.files[0];if(f)open(f,f.name,$('#unit').value)};$('#back').onclick=()=>{$('#viewer').hidden=true;$('#home').hidden=false};for(const a of['x','y','z'])$(`#rot-${a}`).onclick=()=>{rotate90(state.currentModel.root,a);persist();refresh()};$('#reset').onclick=()=>{resetOrientation(state.currentModel.root);persist();refresh()};$('#place').onclick=()=>{placeMode=true;alert('Klepněte na rovnou plochu modelu.')};$('#canvas').onclick=e=>{if(!placeMode)return;const h=viewer.pick(e,state.currentModel.root);if(h){placeNormal(state.currentModel.root,h.face.normal);persist();refresh()}placeMode=false};
$('#analysis').onclick=()=>{const active=state.analysisMode!=='overhang';state.analysisMode=active?'overhang':'normal';state.currentModel.root.traverse(o=>{if(!o.isMesh)return;if(!o.userData.normal)o.userData.normal=o.material;addOverhangAttribute(state.currentModel.root,state.material.overhangSeverityFactor);o.material=active?heatmapMaterial():o.userData.normal});$('#legend').hidden=!active;$('#analysis').setAttribute('aria-pressed',active)};$('#printer').onchange=async e=>{state.printer=printers.find(p=>p.id===e.target.value);viewer.setBed(state.printer);await setSetting('printer',state.printer.id);refresh()};$('#material').onchange=async e=>{state.material=materials.find(m=>m.id===e.target.value);await setSetting('material',state.material.id);if(state.analysisMode==='overhang')$('#analysis').click(),$('#analysis').click()};$('#ar').onclick=()=>startAR(viewer).catch(e=>alert(e.message));
$('#share').onclick=async()=>{const url=new URL('.',location.href).href,data={title:'PrintScope AR',text:'Zkontrolujte si 3D model před tiskem v PrintScope AR.',url};if(navigator.share){try{await navigator.share(data)}catch(e){if(e.name!=='AbortError')alert('Sdílení se nepodařilo.')}return}try{await navigator.clipboard.writeText(url);alert('Odkaz na aplikaci byl zkopírován.')}catch{prompt('Zkopírujte odkaz na aplikaci:',url)}};
const hideInstall=()=>{$('#install').hidden=true;installPrompt=null};addEventListener('beforeinstallprompt',e=>{e.preventDefault();installPrompt=e;$('#install').hidden=false});addEventListener('appinstalled',hideInstall);$('#install').onclick=async()=>{if(!installPrompt)return;const promptEvent=installPrompt;await promptEvent.prompt();await promptEvent.userChoice;hideInstall()};if(matchMedia('(display-mode: standalone)').matches||navigator.standalone)hideInstall();boot();
$('#update-app').onclick=()=>location.reload();
$('#notice-close').onclick=()=>{$('#notice').hidden=true};addEventListener('keydown',e=>{if(e.key==='Escape')$('#notice').hidden=true});
